config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get '/admin/orders/:id/change_sent(.:format)' => 'admin/orders#change_sent'
  
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  get 'users/new'

  get 'users/create'

  get 'users/edit'

  get 'users/update'

  resources :issues
  
  resources :users, :only => [:new, :create,:edit,:update] 
  resources :users do
    member do
      get 'my_orders', :action => :my_orders
    end
  end
  
  resources :addresses
  
  resources :user_sessions

  get 'login' => "user_sessions#new",      :as => :login
  get 'logout' => "user_sessions#destroy", :as => :logout

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route
  post 'user_sessions/create'
  get 'signup' => 'users#new', :as => :signup
  root :to => 'issues#index'

  
  resource :cart, only: [:show]
  resource :carts, only: [:show, :checkout, :checkout_save, :success]
  resources :carts do
    collection do
      get 'checkout', :action => :checkout
      get 'checkout_save', :action => :checkout_save
    end
  end
  resources :order_items, only: [:create, :update, :destroy]
  
  resources :orders

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  has_one :address, :as => :shipping
  accepts_nested_attributes_for :address
  attr_accessible :address_attributes, :payment, :status, :user_id
  
  before_create :set_order_status
  before_save :update_subtotal
  before_save :update_shipping
  before_save :update_total
  
  STATUSES = %i[oczekujące w_realizacji zapłacone zrealizowane]
   
  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
  private
    def set_order_status
      self.status = 'oczekujące'
    end

    def update_subtotal
      self[:subtotal] = subtotal
    end
    
    def update_shipping
      self.shipping = 5.00
    end
    
    def update_total
      self.total = subtotal + self.shipping
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    if current_user
      @orders = Order.where("user_id = ?", current_user.id)
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.build_address
  end

  # GET /orders/1/edit
  def edit
    @order.build_address

  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    if params[:id]
      @order = Order.find(params[:id])
    else
      @order = current_order
    end

    respond_to do |format|
      if @order.update(order_params)
        session[:order_id]=nil
        format.html { redirect_to root_path, notice: 'Dziękujemy za złożenie zamówienia!' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    session[:order_id]=nil
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:status, :total, :payment, :subtotal, :tax, :shipping, :user_id, :created_at, address_attributes: [:id, :order_id, :name, :surname, :street, :house_number, :apartment_number, :city, :zip_code])
  end


end

app/views/admin/orders/annual_sales.html.erb
<p id="notice"><%= notice %></p>

  <p>
    <h3>W sumie sprzedano</h3>
  <%= @order_sum %>
</p>

app/views/admin/orders/change_payment.html.erb
<%= form_for @order, :url => admin_order_path(@order) do |f| %>
    <!-- kod wyświetlający błędy -->
    <p>
      <%= f.label :payment %> <br />
      <%= f.date_select :payment, {:order => [:day, :month, :year],:prompt => true, :start_year => Time.now.year  } %>

    <p><%= f.submit "Submit" %> </p>
<% end %>

app/views/admin/orders/change_sent.html.erb
<%= form_for @item do |f| %>
    <!-- kod wyświetlający błędy -->
    <p>
      <%= f.label :sent %> <br />
      <%= f.select :sent, options_for_select(OrderItem::SENTS) %>
      <%= f.hidden_field :order_id, value: @item.order_id %>

    <p><%= f.submit "Submit" %> </p>
<% end %>

app/views/admin/orders/change_status.html.erb
<%= form_for @order, :url => admin_order_path(@order) do |f| %>
    <!-- kod wyświetlający błędy -->
    <p>
      <%= f.label :status %> <br />
      <%= f.select :status, options_for_select(Order::STATUSES) %>

    <p><%= f.submit "Submit" %> </p>
<% end %>

app/views/admin/orders/order_archives.html.erb
<table>
  <thead>
  <tr>
    <th>Id</th>
    <th>Status</th>
    <th>Data płatności</th>
    <th>Data złożenia</th>
  </tr>
  </thead>

  <tbody>
  <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.status %></td>
        <td><%= order.payment %></td>
        <td><%= order.created_at %></td>
      </tr>
  <% end %>
  </tbody>
</table>