config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get '/admin/orders/:id/change_sent(.:format)' => 'admin/orders#change_sent'
  
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  get 'users/new'

  get 'users/create'

  get 'users/edit'

  get 'users/update'

  resources :issues
  
  resources :users, :only => [:new, :create,:edit,:update] 
  resources :users do
    member do
      get 'my_orders', :action => :my_orders
    end
  end
  
  resources :addresses
  
  resources :user_sessions

  get 'login' => "user_sessions#new",      :as => :login
  get 'logout' => "user_sessions#destroy", :as => :logout

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route
  post 'user_sessions/create'
  get 'signup' => 'users#new', :as => :signup
  root :to => 'issues#index'

  
  resource :cart, only: [:show]
  resource :carts, only: [:show, :checkout, :checkout_save, :success]
  resources :carts do
    collection do
      get 'checkout', :action => :checkout
      get 'checkout_save', :action => :checkout_save
    end
  end
  resources :order_items, only: [:create, :update, :destroy]
  
  resources :orders

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  has_one :address, :as => :shipping
  accepts_nested_attributes_for :address
  attr_accessible :address_attributes, :payment, :status, :user_id
  
  before_create :set_order_status
  before_save :update_subtotal
  before_save :update_shipping
  before_save :update_total
  
  STATUSES = %i[oczekujące w_realizacji zapłacone zrealizowane]
   
  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
  private
    def set_order_status
      self.status = 'oczekujące'
    end

    def update_subtotal
      self[:subtotal] = subtotal
    end
    
    def update_shipping
      self.shipping = 5.00
    end
    
    def update_total
      self.total = subtotal + self.shipping
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    if current_user
      @orders = Order.where("user_id = ?", current_user.id)
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.build_address
  end

  # GET /orders/1/edit
  def edit
    @order.build_address

  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    if params[:id]
      @order = Order.find(params[:id])
    else
      @order = current_order
    end

    respond_to do |format|
      if @order.update(order_params)
        session[:order_id]=nil
        format.html { redirect_to root_path, notice: 'Dziękujemy za złożenie zamówienia!' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    session[:order_id]=nil
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:status, :total, :payment, :subtotal, :tax, :shipping, :user_id, :created_at, address_attributes: [:id, :order_id, :name, :surname, :street, :house_number, :apartment_number, :city, :zip_code])
  end


end

app/views/orders/_form.html.erb
<%= form_for(current_order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.hidden_field :status, :value => 'w realizacji' %>
    </div>
  <div class="field">
    <%= f.hidden_field :payment, :value => @date %>
  </div>

    <%= f.fields_for :address do |o| %>
        <div class="field">
          <%= o.label :name %><br>
          <%= o.text_field :name %>
        </div>
        <p>
          <%= o.label :surname %><br />
          <%= o.text_field :surname %>
        </p>
        <p>
          <%= o.label :street %><br />
          <%= o.text_field :street %>
        </p>
        <p>
          <%= o.label :number %><br />
          <%= o.text_field :number %>
        </p>
        <p>
          <%= o.label :city %><br />
          <%= o.text_field :city %>
        </p>
        <p>
          <%= o.label :zip_code %><br />
          <%= o.text_field :zip_code %>
        </p>
        <div class="field">
          <%= f.hidden_field :address_id, :value => @order.id %>
        </div>
        <div class="field">
          <%= f.hidden_field :address_type, :value => "guest" %>
        </div>
    <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="row">
	<div class="col-md-12">
		<% if current_user %>
		<h1>Historia zamówień</h1>
			<% @orders.each do |order| %>
			<div class="table-respinsive">
				<table class="table">
					<thead>
						<tr>
							<th>Wartość</th>
							<th>Cena wysyłki</th>
							<th>Wartość z wysyłką</th>
							<th>Status</th>
							<% if current_user.role == "koordynator" %><th>Termin zapłaty</th><% end %>
							<th>Data Utworzenia</th>
						</tr>
					</thead>
					<tbody>
		      <tr class="info">
		        <td><%= order.subtotal %></td>
		        <td><%= order.shipping %></td>
		        <td><%= order.total%></td>
		        <td><%= order.status %></td>
						<% if current_user.role == "koordynator" %>
			        <td>
								<% if !order.payment.nil? %>
									<%= order.payment%>
								<% else %>
									n/a
								<% end %>
							</td>
						<% end %>
						<td><%= order.created_at %></td>
		      </tr>
					<tr>
						<td>Dane wysyłki:</td>
						<% if current_user.role == "koordynator" %><td colspan="5"><% else %><td colspan="4"><% end %>
							<%= order.address.name %> <%= order.address.surname %>, <%= order.address.street %> <%= order.address.house_number%>/<%= order.address.apartment_number %>, <%= order.address.zip_code %> <%= order.address.city %>
						</td>
					</tr>
					<tr>
						<% if current_user.role == "koordynator" %><td colspan="6"><% else %><td colspan="5"><% end %>
							<table class="table table-striped table-hover">
								<thead>
									<th>ID Krajki</th>
									<th>Nazwa Krajki</th>
									<th>Cena jedn.</th>
									<th>Ilość</th>
									<th>Cena</th>
									<th>Wysłano</th>
								</thead>
								<tbody>
									<% order.order_items.each do |item| %>
										<tr>
											<td><%= item.issue_id %></td>
											<td><%= item.issue.title %></td>
											<td><%= item.unit_price %></td>
											<td><%= item.quantity %></td>
											<td><%= item.total_price %></td>
											<% if item.sent == "true" %><td class="success">tak<% else %><td>nie<% end %></td>
										</tr>
									<% end %>
								</tbody>
							</table>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<% end %>
		<% else %><!-- end of current user -->
			<p class="error"><%= link_to "Zaloguj się", :login %>, aby podejrzeć historię zamowień!</p>
		<% end %>
	</div>
</div>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @order.payment %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>