config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get '/admin/orders/:id/change_sent(.:format)' => 'admin/orders#change_sent'
  
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  get 'users/new'

  get 'users/create'

  get 'users/edit'

  get 'users/update'

  resources :issues
  
  resources :users, :only => [:new, :create,:edit,:update] 
  resources :users do
    member do
      get 'my_orders', :action => :my_orders
    end
  end
  
  resources :addresses
  
  resources :user_sessions

  get 'login' => "user_sessions#new",      :as => :login
  get 'logout' => "user_sessions#destroy", :as => :logout

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route
  post 'user_sessions/create'
  get 'signup' => 'users#new', :as => :signup
  root :to => 'issues#index'

  
  resource :cart, only: [:show]
  resource :carts, only: [:show, :checkout, :checkout_save, :success]
  resources :carts do
    collection do
      get 'checkout', :action => :checkout
      get 'checkout_save', :action => :checkout_save
    end
  end
  resources :order_items, only: [:create, :update, :destroy]
  
  resources :orders

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
  
  def checkout
    @items = current_order.order_items
    @order = current_order
    @order.build_address
    
  end

  def success
    render :success
  end
  
  def modify_volume
    order_items.each do |item|
      @issue = Issue.find(item.issue_id)
      current = @issue.volume
      current = current - item.quantity
      @issue.update_attributes(:volume => current)
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
		<div class="col-md-2">
			<%= image_tag issue.picture.url(:thumb) %>
		</div>
    <div class="col-md-6 issue-desc">
      <h4>Tytuł: <span><%= issue.title %></span></h4>
			<p class="price">Cena jednostkowa: <span><%= number_to_currency issue.price %></span></p>
			<p>Numer: <span><%= issue.mark %></span></p>
			<p>Data: <span><%= issue.date %></span></p>
    </div>
    <div class="col-md-4">
      <%= form_for order_item, remote: true do |f| %>
				<div class="form-group">
	      		<%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
	      		<%= f.hidden_field :issue_id, value: issue.id %>
				</div>
				<div class="form-group">
	      	<%= f.submit "Zmień ilość", class: "btn btn-primary" %>
	      	<%= link_to "Usuń", order_item, { data: { confirm: "Czy na pewno chcesz usunąć '#{order_item.issue.title}' z koszyka?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
				</div>
			<% end %>
    </div>
    
  </div>
</div>

app/views/carts/_carts_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= issue.title %></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :issue_id, value: issue.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.issue.title}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>
    
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    Twój koszyk jest pusty.  Wróć do <%= link_to "sklepu", root_path %>, aby dodać Krajki do koszyka.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', issue: order_item.issue, order_item: order_item, show_total: true %>
  <% end %>
	<div class="well">
		<div class="row">
			<div class="col-xs-12">
				<h4>Suma: <%= number_to_currency current_order.subtotal %></h4>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<%= link_to "Przejdż do kasy", checkout_carts_path, :class => "btn btn-success checkout-button" %>
		</div>
	</div>
<% end %>

app/views/carts/checkout.html.erb
<div class="row">
  <div class=" col-md-12">
    <% if !@item.nil? && @item.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <% if @items.size == 0 %>
        <p class="text-center">
          Twój koszyk jest pusty. Proszę <%= link_to "wróć", root_path %> i dodaj coś do koszyka.
        </p>
    <% else %>
        <% @items.each do |item| %>
            <div class="row">

              <div class="col-md-6">
                <div class="row">
                  <div class="col-md-6">
                    <p><%= image_tag item.issue.picture.url(:thumb) %></p>
                  </div>
                  <div class="col-md-6">
                    <h4><%= item.issue.title %></h4>
                  </div>
                </div>
              </div>

              <div class="col-md-6">
                <div class="row">
                  <div class="col-md-12">
                    <div class="col-md-6">
                      <% #if item.commision == true %>
                          <!--Zakup w komisie-->
                      <% #end %>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <h4 class="text-right">Cena:
                          <span style="color: green"><%= number_to_currency item.unit_price %></span></h4>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

            </div>
            <!-- end of row -->
        <% end %>
        <h4 class="text-right">Suma:
          <%= "#{number_to_currency current_order.subtotal}" %></h4>
        <h4 class="text-right">Dostawa:
          <%= "#{number_to_currency current_order.shipping}" %></h4>
        <h4 class="text-right">Suma całkowita: <span style="color: green">
        <%= "#{number_to_currency current_order.total}" %></span></h4>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= form_for @order, :html => {:class => 'form-horizontal'} do |o| %>
        <% if @order.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@order.errors.count, "error") %> prohibited this checkout from being saved:</h2>

              <ul>
                <% @order.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <h1>Adres</h1>
        <%= o.fields_for :address do |b| %>
            <div class="form-group">
              <%= b.label :name, "Imię", :class => 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <%= b.text_field :name, id: 'name', :class => 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <%= b.label :surname, "Nazwisko", :class => 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <%= b.text_field :surname, :class => 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= b.label :street, "Ulica", :class => 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <%= b.text_field :street, :class => 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= b.label :house_number, "Nr budynku", :class => 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <%= b.text_field :house_number, :class => 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <%= b.label :apartment_number, "Nr lokalu", :class => 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <%= b.text_field :apartment_number, :class => 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <%= b.label :city, "Miasto", :class => 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <%= b.text_field :city, :class => 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= b.label :zip_code, "Kod pocztowy", :class => 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <%= b.text_field :zip_code, :class => 'form-control' %>
              </div>
            </div>
        <% end %>
				<%= o.hidden_field :order_status_id, value: '2' %>
        <%= o.hidden_field :check, value: 'true' %>
        <% if current_user %>
            <%= o.hidden_field :user_id, value: current_user.id %>
        <%end%>

        <% if current_user && current_user.role == 'koordynator' %>
            <div class="form-group" -->
              <%= o.label "Tarmin zapłaty", :class => 'col-sm-2 control-label' %>
              <div class="col-sm-10">
              <%= o.date_select :payment, :class => 'form-control' %>
                </div>
            </div>
        <% end %>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= o.submit "Złóż zamówienie", :class => "btn btn-success" %>
          </div>
        </div>
    <% end %>
    <% if current_user %>
        <div class="form-horizontal">
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button class="btn btn-primary" onclick="update_address_fields()" id="update_fields_button">Użyj mojego
                adresu
              </button>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

<script>
    function update_address_fields() {
        <% if current_user %>
        var customer_name = "<%= current_user.address.name %>";
        var customer_surname = "<%= current_user.address.surname %>";
        var customer_street = "<%= current_user.address.street %>";
        var customer_house = "<%= current_user.address.house_number %>";
        var customer_apartment = "<%= current_user.address.apartment_number %>";
        var customer_city = "<%= current_user.address.city %>";
        var customer_zip = "<%= current_user.address.zip_code %>";
        //console.log(customer_name + " " + customer_surname + " " + customer_street + " " + customer_house + " " + customer_city + " " + customer_zip);
        if (customer_name == "" || customer_surname == "" || customer_street == "" || customer_house == "" || customer_city == "" || customer_zip == "") {
            alert("Brak adresu lub niepełny, proszę wpisać adres ręcznie!");
            $("#update_fields_button").prop("disabled", true);
        } else {
            $("#name").val(customer_name);
            $("#order_address_attributes_surname").val(customer_surname);
            $("#order_address_attributes_street").val(customer_street);
            $("#order_address_attributes_house_number").val(customer_house);
            $("#order_address_attributes_apartment_number").val(customer_apartment);
            $("#order_address_attributes_city").val(customer_city);
            $("#order_address_attributes_zip_code").val(customer_zip);
        }
        <%end%>
    }
</script>

app/views/carts/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("Wystąpił problem. Proszę spróbować ponownie.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/carts/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/carts/success.html.erb
<div class="row">
	<div class="col-md-12">
		<p class="success">BRAWO KURWA, HAJS NA TO KONTO</p>
		<p>Numer konta: xxxx xxxx xxxx xxxx xxxx xxxx</p>
		<p>Krajki, ulica Harcerska 13a/7, Zadupie</p>
	</div>
</div>

app/views/carts/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text').html_safe %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart').html_safe %>")