config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get '/admin/orders/:id/change_sent(.:format)' => 'admin/orders#change_sent'
  
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  get 'users/new'

  get 'users/create'

  get 'users/edit'

  get 'users/update'

  resources :issues
  
  resources :users, :only => [:new, :create,:edit,:update] 
  resources :users do
    member do
      get 'my_orders', :action => :my_orders
    end
  end
  
  resources :addresses
  
  resources :user_sessions

  get 'login' => "user_sessions#new",      :as => :login
  get 'logout' => "user_sessions#destroy", :as => :logout

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route
  post 'user_sessions/create'
  get 'signup' => 'users#new', :as => :signup
  root :to => 'issues#index'

  
  resource :cart, only: [:show]
  resource :carts, only: [:show, :checkout, :checkout_save, :success]
  resources :carts do
    collection do
      get 'checkout', :action => :checkout
      get 'checkout_save', :action => :checkout_save
    end
  end
  resources :order_items, only: [:create, :update, :destroy]
  
  resources :orders

end

app/views/layouts/_cart_text.html.erb
<i class="fa fa-shopping-cart"></i> <%= link_to "#{current_order.order_items.size} Artykuł(ów) w koszyku ( #{number_to_currency current_order.subtotal} )", cart_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScoutsBeta</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<%= favicon_link_tag 'favicons/favicon.ico' %>
	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
  <div class="container">
		<div class="row">
        
	  
	  <nav class="navbar navbar-default">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#primary-nav">
		    	<span class="sr-only">Toggle navigation</span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		    </button>
		    <%= link_to image_tag("logo_small.png"), root_path, class: "navbar-brand" %>
		  </div>
			
			<div class="collapse navbar-collapse" id="primary-nav">
				<ul class="nav navbar-nav">
					<li><%= link_to "Strona Główna", root_path%></li>
				  <% if current_user %>
		         <li><%= link_to "Edytuj profil", edit_user_path(current_user.id) %></li>
		         <li><%= link_to "Historia zamówień", orders_path %></li>
		         <li><%= link_to "Wyloguj", :logout %></li>
					<% else %>
				      <li><%= link_to "Zarejestruj się", new_user_path %></li>
				      <li><%= link_to "Zaloguj się", :login %></li>
				  <% end %>
				</ul>
				<div class="nav navbar-nav navbar-right">
					<ul class="nav navbar-nav">
						<li><div class="cart-text"><%= render 'layouts/cart_text' %></div></li>
					</ul>
				</div>
			</div>
			
	  </nav>
    </div>
	</div>
	
	<div class="container content">
		<div class="row">
			<div class="col-md-12 informative">
				<div class="messages"></div>
				<p id="notice" class="text-success"><%= notice %></p>
				<p id="alert" class="text-danger"><%= alert %></p>
			</div>
		</div>
    <%= yield %>
	</div>
	<div class="container footer">
		<div class="row">
			<div class="col-xs-12 col-md-3">
				<%= link_to image_tag("logo_small.png"), root_path, :class => "footer-logo" %>
			</div>
			<div class="col-xs-12 col-md-9">
				<div class="row">
					<div class="col-xs-6 col-md-6 text-right">
						<%= link_to image_tag("epi.png"), "http://www.epi.uj.edu.pl", :class => "footer-logo" %>
					</div>
					<div class="col-xs-6 col-md-6 text-right">
						<%= link_to image_tag("uj.png"), "http://www.uj.edu.pl", :class => "footer-logo" %>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="footer-desc">
							<p class="text-right">
								<a href="https://www.facebook.com/oli.peech">
									<i class="fa fa-facebook-official"></i>
								</a> 
								<a href="https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile">
									<i class="fa fa-linkedin"></i>
								</a>
								<a href="mailto:agustkiewicz@gmail.com">
									<i class="fa fa-envelope"></i>
								</a>
								Projekt i wykonanie: Aleksander Gustkiewicz 2015 <i class="fa fa-copyright"></i>
							</p>
							<p class="text-right">Uniwersytet Jagielloński, Wydział Zarządzania i Komunikacji Społecznej, Elektroniczne Przetwarzanie Informacji</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

</body>
</html>